### ISSUE TITLE
Accept RFC-compliant zonefile

### ISSUE THREAD

**Issue by thinkl33t** [pwaring/dns-sync-zone#10]
The current zonefile accepted by this script technically isn't a zonefile, its a list of API commands.

It would be useful to accept a bind-style / RFC 1035 formatted zonefile.  These can be downloaded from mythic beasts to pre-seed a domain's zone in the top-right menu of the DNS editing page, and can be parsed / verified by the python `dnszone` package

We currently use a sed script to turn these into list of API commands to feed to dns-zone-sync.  This collapses whitespace into a single space (limitation of the API), adds `ADD` to the beginning of the line, and removes the `$ORIGIN` line.

```
sed -e 's/ \+/ /g' -e 's/^/ADD /' -e '/$ORIGIN/d' zone.file
```

**Comment by pwaring** [comment]
This is something I wish I'd thought of when I wrote the original script! It's a very good idea, and accepting `$ORIGIN` as the first line would also fix part of #4 (checking that the zone file matches the `--zone` parameter). I'll have a look at RFC 1035 as it's been a long time since I used BIND, and I'm inclined to make this a breaking change (I'll have to update all my files, but I think the effort is worth it).

**Comment by thinkl33t** [comment]
Another option would be to have a different argument for each, and continue
to accept the old format for now

**Comment by pwaring** [comment]
I think to keep the main script clean I'll make this a breaking change in 1.0.0, but provide a helper script to convert files to the new format for anyone who already has lots of zones in the old format. I have enough files that it's worth me writing a conversion script anyway.
