### ISSUE TITLE
Whitespace separation

### ISSUE THREAD

**Issue by thinkl33t** [pwaring/dns-sync-zone#12]
dns-sync-zone splits on one or more whitespace characters, whereas the mythic beasts api splits based on a single character.  This means zonefiles that pass validation can fail when being sent to the API.

Personally, i prefer dns-sync-zone's behaviour, as it makes the input files more readable, So would prefer to if dns-sync-zone reassembled the command to be sent with single whitespace characters before sending it to the API.

**Comment by pwaring** [comment]
Agreed, I think it would be best for the script to be fairly liberal in what it accepts, and then reformat the input to match MB's API requirements. Since the script already breaks up the record for validation it shouldn't be too difficult to implement this change, I think this line is the only one which would need to be altered:

`sync_commands.append(zone_record)`

`zone_record` would be split by white space and then joined by a single space, which I think you can do in a single line.

**Comment by pwaring** [comment]
In fact, given how simple this change is, I think I can do it this evening - leave it with me.

**Comment by thinkl33t** [comment]
You may need to special-case the reassembly for TXT records, in theory they could contain whitespace - i don't know if any commonly used records do though.

**Comment by pwaring** [comment]
SPF records contain whitespace, but I don't think any whitespace beyond the first space is relevant (e.g. 'abc[space][space]xyz' and 'abc[space]xyz' are treated the same). Any newlines would cause problems but then they would break the 'one record per line' rule anyway.
